import { newsArrType } from '@/types/news';

const newsArr: newsArrType[] = [
  {
    id: 'n33',
    title: '21 июня',
    pretitle: 'Арзамас',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-arzamas-21.06.2022',
  },
  {
    id: 'n32',
    title: '13 июня',
    pretitle: 'Железногорск',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-zheleznogorsk-14.06.2022',
  },
  {
    id: 'n31',
    title: '10 июня',
    pretitle: 'Брянск',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-bryansk-10.06.2022',
  },
  {
    id: 'n30',
    title: '07 июня',
    pretitle: 'Великие Луки',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-velikie-luki-07.06.2022',
  },
  {
    id: 'n29',
    title: '25 мая',
    pretitle: 'Липецк',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-lipeck-25.05.2022',
  },
  {
    id: 'n28',
    title: '24 мая',
    pretitle: 'Кострома',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-kostroma-24.05.2022',
  },
  {
    id: 'n27',
    title: '19 мая',
    pretitle: 'Череповец',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-cherepovets-19.05.2022',
  },
  {
    id: 'n26',
    title: '29 апреля',
    pretitle: 'Старый Оскол',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-stariy-oskol-29.04.2022',
  },
  {
    id: 'n25',
    title: '26 апреля',
    pretitle: 'Ставрополь',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-stavropol-26.04.2022',
  },
  {
    id: 'n24',
    title: '25 апреля',
    pretitle: 'Черкесск',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-cherkessk-25.04.2022',
  },
  {
    id: 'n23',
    title: '11 апреля',
    pretitle: 'Великие Луки',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-velikie-luki-11.04.2022',
  },
  {
    id: 'n22',
    title: '07 апреля',
    pretitle: 'Саранск',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-saransk-07.04.2022',
  },
  {
    id: 'n21',
    title: '06 апреля',
    pretitle: 'Арзамас',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-arzamas-06.04.2022',
  },
  {
    id: 'n20',
    title: '05 апреля',
    pretitle: 'Нижний Новгород',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-nizhniy-novgorod-05.04.2022',
  },
  {
    id: 'n19',
    title: '29 марта',
    pretitle: 'Сортавала',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-sortavala-29.03.2022',
  },
  {
    id: 'n18',
    title: '15 марта',
    pretitle: 'Ставрополь',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-stavropol-15.03.2022',
  },
  {
    id: 'n17',
    title: '14 марта',
    pretitle: 'Черкесск',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-cherkessk-14.03.2022',
  },
  {
    id: 'n16',
    title: '10 марта',
    pretitle: 'Железногорск',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-zheleznogorsk-10.03.2022',
  },
  {
    id: 'n15',
    title: '01 марта',
    pretitle: 'Хасавюрт',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-hasavyurt-01.03.2022',
  },
  {
    id: 'n14',
    title: '01 марта',
    pretitle: 'Старый Оскол',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-stariy-oskol-01.03.2022',
  },
  {
    id: 'n13',
    title: '25 февраля',
    pretitle: 'Шахты',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-shahti-25.02.2022',
  },
  {
    id: 'n12',
    title: '10 февраля',
    pretitle: 'Саранск',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-saransk-10.02.2022',
  },
  {
    id: 'n11',
    title: '09 февраля',
    pretitle: 'Арзамас',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-arzamas-09.02.2022',
  },
  {
    id: 'n10',
    title: '08 февраля',
    pretitle: 'Нижний Новгород',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-nizhniy-novgorod-08.02.2022',
  },
  {
    id: 'n9',
    title: '25 января',
    pretitle: 'Старый Оскол',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-stariy-oskol-25.01.2022',
  },
  {
    id: 'n8',
    title: '18 января',
    pretitle: 'Ставрополь',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-stavropol-18.01.2022',
  },
  {
    id: 'n7',
    title: '22 декабря',
    pretitle: 'Арзамас',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-arzamas-22.12.2021',
  },
  {
    id: 'n6',
    title: '21 декабря',
    pretitle: 'Нижний Новгород',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-nizhniy-novgorod-21.12.2021',
  },
  {
    id: 'n6',
    title: '21 декабря',
    pretitle: 'Волхов',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-volhov-21.12.2021',
  },
  {
    id: 'n5',
    title: '21 декабря',
    pretitle: 'Старый Оскол',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-stariy-oskol-21.12.2021',
  },
  {
    id: 'n4',
    title: '20 декабря',
    pretitle: 'Великие Луки',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-velikie-luki-20.12.2021',
  },
  {
    id: 'n3',
    title: '16 ноября',
    pretitle: 'Старый Оскол',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-stariy-oskol-16.11.2021',
  },
  {
    id: 'n2',
    title: '11 ноября',
    pretitle: 'Ставрополь',
    buttonText: 'Записаться на приём',
    link: 'priem-v-gorode-stavropol-02-11-2021',
  },
  {
    id: 'n1',
    title: '9 ноября',
    pretitle: 'город Владимир',
    buttonText: 'Записаться на консультацию',
    link: 'priem-v-gorode-vladimir-09-11-2021',
  },
];

export default newsArr;
